package com.consentmanager.models;

import java.time.LocalDate;

public class Admin {
    private Integer adminId;
    private Integer credentialId; // Foreign key to Credential table
    private String firstName;
    private String middleName;
    private String lastName;
    private String email;
    private String mobileNo;
    private LocalDate dateOfBirth; // Stored as TEXT (YYYY-MM-DD) in DB

    // Default constructor
    public Admin() {
    }

    // Constructor for creation (adminId generated by DB)
    public Admin(Integer credentialId, String firstName, String middleName, String lastName, String email, String mobileNo, LocalDate dateOfBirth) {
        this.credentialId = credentialId;
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.email = email;
        this.mobileNo = mobileNo;
        this.dateOfBirth = dateOfBirth;
    }

    // Full constructor (when retrieving from DB)
    public Admin(Integer adminId, Integer credentialId, String firstName, String middleName, String lastName, String email, String mobileNo, LocalDate dateOfBirth) {
        this.adminId = adminId;
        this.credentialId = credentialId;
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.email = email;
        this.mobileNo = mobileNo;
        this.dateOfBirth = dateOfBirth;
    }

    // Getters and Setters
    public Integer getAdminId() {
        return adminId;
    }

    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    public Integer getCredentialId() {
        return credentialId;
    }

    public void setCredentialId(Integer credentialId) {
        this.credentialId = credentialId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getMiddleName() {
        return middleName;
    }

    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getMobileNo() {
        return mobileNo;
    }

    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }

    public LocalDate getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    @Override
    public String toString() {
        return "Admin{" +
                "adminId=" + adminId +
                ", credentialId=" + credentialId +
                ", firstName='" + firstName + '\'' +
                ", middleName='" + middleName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", email='" + email + '\'' +
                ", mobileNo='" + mobileNo + '\'' +
                ", dateOfBirth=" + dateOfBirth +
                '}';
    }
}
