package com.consentmanager.models;

public class Credential {
    private Integer credentialId;
    private String username;
    private String password; // This will store the hashed password
    private String role; // "provider", "seeker", "admin"

    // Default constructor (needed for some frameworks/libraries, e.g., Jackson)
    public Credential() {
    }

    // Constructor for creating a new credential before saving (ID might be generated by DB)
    public Credential(String username, String password, String role) {
        this.username = username;
        this.password = password;
        this.role = role;
    }

    // Full constructor (when retrieving from DB)
    public Credential(Integer credentialId, String username, String password, String role) {
        this.credentialId = credentialId;
        this.username = username;
        this.password = password;
        this.role = role;
    }

    // Getters and Setters
    public Integer getCredentialId() {
        return credentialId;
    }

    public void setCredentialId(Integer credentialId) {
        this.credentialId = credentialId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    @Override
    public String toString() {
        return "Credential{" +
                "credentialId=" + credentialId +
                ", username='" + username + '\'' +
                ", role='" + role + '\'' +
                // Password is intentionally omitted from toString for security
                '}';
    }
}
