package com.consentmanager.models;

import java.time.LocalDate;
import java.time.LocalDateTime;

public class ProviderBacklog {
    private Integer backlogId;
    private String username;
    private String password; // Hashed
    private String role; // Should always be "provider"
    private String firstName;
    private String middleName;
    private String lastName;
    private String email;
    private LocalDate dateOfBirth;
    private String mobileNo;
    private Integer age;
    private String gender; // "Male", "Female"
    private String publicKey;
    private String status; // "pending", "rejected", "approved"
    private LocalDateTime createdAt; // Stored as TEXT (ISO8601) in DB

    // Default constructor
    public ProviderBacklog() {
    }

    // Constructor for creation (backlogId, createdAt generated by DB or on save)
    public ProviderBacklog(String username, String password, String role, String firstName, String middleName, String lastName, String email, LocalDate dateOfBirth, String mobileNo, Integer age, String gender, String publicKey, String status) {
        this.username = username;
        this.password = password;
        this.role = role;
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.email = email;
        this.dateOfBirth = dateOfBirth;
        this.mobileNo = mobileNo;
        this.age = age;
        this.gender = gender;
        this.publicKey = publicKey;
        this.status = status;
    }


    // Full constructor
    public ProviderBacklog(Integer backlogId, String username, String password, String role, String firstName, String middleName, String lastName, String email, LocalDate dateOfBirth, String mobileNo, Integer age, String gender, String publicKey, String status, LocalDateTime createdAt) {
        this.backlogId = backlogId;
        this.username = username;
        this.password = password;
        this.role = role;
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.email = email;
        this.dateOfBirth = dateOfBirth;
        this.mobileNo = mobileNo;
        this.age = age;
        this.gender = gender;
        this.publicKey = publicKey;
        this.status = status;
        this.createdAt = createdAt;
    }

    // Getters and Setters
    public Integer getBacklogId() {
        return backlogId;
    }

    public void setBacklogId(Integer backlogId) {
        this.backlogId = backlogId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getMiddleName() {
        return middleName;
    }

    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public LocalDate getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public String getMobileNo() {
        return mobileNo;
    }

    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getPublicKey() {
        return publicKey;
    }

    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        return "ProviderBacklog{" +
                "backlogId=" + backlogId +
                ", username='" + username + '\'' +
                ", email='" + email + '\'' +
                ", status='" + status + '\'' +
                ", createdAt=" + createdAt +
                '}';
    }
}
